/**
 * All 54 African countries (UN/AU member states) for location selection.
 */
export const AFRICAN_COUNTRIES: { id: string; name: string }[] = [
  { id: "algeria", name: "Algeria" },
  { id: "angola", name: "Angola" },
  { id: "benin", name: "Benin" },
  { id: "botswana", name: "Botswana" },
  { id: "burkina-faso", name: "Burkina Faso" },
  { id: "burundi", name: "Burundi" },
  { id: "cabo-verde", name: "Cabo Verde" },
  { id: "cameroon", name: "Cameroon" },
  { id: "central-african-republic", name: "Central African Republic" },
  { id: "chad", name: "Chad" },
  { id: "comoros", name: "Comoros" },
  { id: "congo-democratic", name: "Congo (Democratic Republic)" },
  { id: "congo-republic", name: "Congo (Republic)" },
  { id: "cote-d-ivoire", name: "Côte d'Ivoire" },
  { id: "djibouti", name: "Djibouti" },
  { id: "egypt", name: "Egypt" },
  { id: "equatorial-guinea", name: "Equatorial Guinea" },
  { id: "eritrea", name: "Eritrea" },
  { id: "eswatini", name: "Eswatini" },
  { id: "ethiopia", name: "Ethiopia" },
  { id: "gabon", name: "Gabon" },
  { id: "gambia", name: "Gambia" },
  { id: "ghana", name: "Ghana" },
  { id: "guinea", name: "Guinea" },
  { id: "guinea-bissau", name: "Guinea-Bissau" },
  { id: "kenya", name: "Kenya" },
  { id: "lesotho", name: "Lesotho" },
  { id: "liberia", name: "Liberia" },
  { id: "libya", name: "Libya" },
  { id: "madagascar", name: "Madagascar" },
  { id: "malawi", name: "Malawi" },
  { id: "mali", name: "Mali" },
  { id: "mauritania", name: "Mauritania" },
  { id: "mauritius", name: "Mauritius" },
  { id: "morocco", name: "Morocco" },
  { id: "mozambique", name: "Mozambique" },
  { id: "namibia", name: "Namibia" },
  { id: "niger", name: "Niger" },
  { id: "nigeria", name: "Nigeria" },
  { id: "rwanda", name: "Rwanda" },
  { id: "sao-tome-and-principe", name: "Sao Tome and Principe" },
  { id: "senegal", name: "Senegal" },
  { id: "seychelles", name: "Seychelles" },
  { id: "sierra-leone", name: "Sierra Leone" },
  { id: "somalia", name: "Somalia" },
  { id: "south-africa", name: "South Africa" },
  { id: "south-sudan", name: "South Sudan" },
  { id: "sudan", name: "Sudan" },
  { id: "tanzania", name: "Tanzania" },
  { id: "togo", name: "Togo" },
  { id: "tunisia", name: "Tunisia" },
  { id: "uganda", name: "Uganda" },
  { id: "zambia", name: "Zambia" },
  { id: "zimbabwe", name: "Zimbabwe" },
];
