import type { DailySaleRow } from '@/hooks/api/production_transaction';
import { buildFarmAdminReport } from './buildFarmAdminReport';
import type { FarmAdminReport } from './farmAdminReport.types';

export type MonthlyDocMeta = {
  id: string; // YYYY-MM
  year: number;
  month: number;
  label: string;
  from: string;
  to: string;
  farmName: string;
  recordCount: number;
  milkQuantity: number;
  revenue: number;
  autoGenerated: boolean;
  chartCount: number;
  hasData: boolean;
};

export type AutoMonthlyPackage = {
  meta: MonthlyDocMeta;
  report: FarmAdminReport;
};

function formatYmd(d: Date) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function monthBounds(year: number, monthIndex0: number) {
  const from = new Date(year, monthIndex0, 1);
  const to = new Date(year, monthIndex0 + 1, 0);
  const today = new Date();
  const end =
    year === today.getFullYear() && monthIndex0 === today.getMonth() && to > today
      ? today
      : to;
  return { from: formatYmd(from), to: formatYmd(end) };
}

export function monthKeyFromDate(value: string | Date | undefined | null) {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) {
    const s = String(value);
    return s.length >= 7 ? s.slice(0, 7) : '';
  }
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

/**
 * Automatically process raw farm records into monthly documentation packages.
 * For each month: aggregates KPIs, builds charts, and prepares the admin report.
 */
export function autoGenerateMonthlyPackages(input: {
  year: number;
  productionRows: any[];
  usageRows: DailySaleRow[];
  transactionRows?: Array<{
    date?: string;
    productType?: string;
    usageCategory?: string;
    quantity?: number;
  }>;
  generatedBy?: string;
  defaultFarmName?: string;
}): AutoMonthlyPackage[] {
  const {
    year,
    productionRows,
    usageRows,
    transactionRows = [],
    generatedBy,
    defaultFarmName,
  } = input;
  const now = new Date();
  const lastMonthIndex =
    year < now.getFullYear() ? 11 : year > now.getFullYear() ? -1 : now.getMonth();

  const packages: AutoMonthlyPackage[] = [];

  for (let m = 0; m <= lastMonthIndex; m++) {
    const id = `${year}-${String(m + 1).padStart(2, '0')}`;
    const bounds = monthBounds(year, m);
    const label = new Date(year, m, 1).toLocaleDateString('en-GB', {
      month: 'long',
      year: 'numeric',
    });

    const monthProd = productionRows.filter(
      (r) => monthKeyFromDate(r.productionDate) === id
    );
    const monthUsage = usageRows.filter((r) => monthKeyFromDate(r.date) === id);
    const monthTx = transactionRows.filter((r) => monthKeyFromDate(r.date) === id);

    const farmName =
      monthProd.find((r) => r?.farm?.name)?.farm?.name ||
      monthUsage.find((r) => r.farmName)?.farmName ||
      defaultFarmName ||
      'Farm';

    const report = buildFarmAdminReport({
      farmName,
      from: bounds.from,
      to: bounds.to,
      generatedBy: generatedBy || 'System (auto)',
      productionRows: monthProd,
      usageRows: monthUsage,
      transactionRows: monthTx,
    });

    packages.push({
      meta: {
        id,
        year,
        month: m + 1,
        label,
        from: bounds.from,
        to: bounds.to,
        farmName,
        recordCount: report.kpis.totalRecords,
        milkQuantity: report.kpis.milkQuantity,
        revenue: report.kpis.revenue,
        autoGenerated: true,
        chartCount: report.charts.filter((c) => c.data.some((d) => d.value > 0)).length,
        hasData: monthProd.length > 0 || monthUsage.length > 0,
      },
      report,
    });
  }

  return packages.reverse();
}
