import type { DailySaleRow } from '@/hooks/api/production_transaction';
import type {
  CattleProduction,
  DailyProduction,
  DailyUsage,
  FarmAdminReport,
  FarmAdminReportInput,
  ProductSummary,
  ReportChartSpec,
  SessionSummary,
  MilkDisposition,
} from './farmAdminReport.types';
import { fmtDate } from './reportBrand';

function unitFor(product: string) {
  return String(product || '').toUpperCase() === 'MILK' ? 'L' : 'kg';
}

function sessionKey(raw: string | undefined | null): 'Morning' | 'Evening' | 'Other' {
  const s = String(raw || '').toUpperCase();
  if (s === 'MORNING') return 'Morning';
  if (s === 'EVENING') return 'Evening';
  return 'Other';
}

function dayKey(value: string | Date | undefined | null) {
  if (!value) return '';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value).slice(0, 10);
  return d.toISOString().slice(0, 10);
}

/** Automatically derive chart specs from summarized farm data. */
export function buildAutoCharts(
  report: Omit<FarmAdminReport, 'charts' | 'autoGenerated'>
): ReportChartSpec[] {
  const charts: ReportChartSpec[] = [
    {
      id: 'milk-consumed',
      title: 'Milk consumed',
      purpose:
        'How was milk disposition split this month? Sold, on-farm use, umucunda, and waste/lost.',
      type: 'donut',
      unit: 'L',
      data: [
        {
          label: 'Sold',
          value: report.milkDisposition.sold,
          color: '#3b82f6',
        },
        {
          label: 'Consumed on farm',
          value: report.milkDisposition.consumedOnFarm,
          color: '#f59e0b',
        },
        {
          label: 'Consumed by umucunda',
          value: report.milkDisposition.consumedByUmucunda,
          color: '#22c55e',
        },
        {
          label: 'Waste or lost',
          value: report.milkDisposition.wasteOrLost,
          color: '#ef4444',
        },
      ],
    },
    {
      id: 'by-product',
      title: 'Production by product',
      purpose: 'What is the farm producing this period?',
      type: 'hbar',
      data: report.byProduct.map((p) => ({ label: p.product, value: p.quantity })),
    },
    {
      id: 'by-session',
      title: 'Morning vs evening',
      purpose: 'When is most milk recorded?',
      type: 'share',
      data: report.bySession.map((s) => ({
        label: s.session,
        value: s.quantity,
        color:
          s.session === 'Morning' ? '#f59e0b' : s.session === 'Evening' ? '#3b82f6' : '#64748b',
      })),
    },
    {
      id: 'daily-trend',
      title: 'Daily production trend',
      purpose:
        'Show whether production is increasing or declining across the month. Recommended view: full month days.',
      type: 'line',
      unit: 'quantity',
      yAxisLabel: 'Quantity',
      data: report.byDay.map((d) => ({
        label: fmtDate(d.date).replace(/ \d{4}$/, ''),
        value: d.quantity,
      })),
      series: [
        {
          name: 'Total production',
          color: '#3b82f6',
          points: report.byDay.map((d) => ({
            label: fmtDate(d.date).replace(/ \d{4}$/, ''),
            value: d.quantity,
          })),
        },
        {
          name: 'Morning',
          color: '#f59e0b',
          points: report.byDay.map((d) => ({
            label: fmtDate(d.date).replace(/ \d{4}$/, ''),
            value: d.morning,
          })),
        },
        {
          name: 'Evening',
          color: '#22c55e',
          points: report.byDay.map((d) => ({
            label: fmtDate(d.date).replace(/ \d{4}$/, ''),
            value: d.evening,
          })),
        },
      ],
    },
    {
      id: 'by-cattle',
      title: 'Top producing cattle',
      purpose: 'Which animals contribute most this month?',
      type: 'hbar',
      data: report.byCattle.slice(0, 8).map((c) => ({ label: c.cattle, value: c.quantity })),
    },
  ];

  if (report.usageByDay.length) {
    charts.push({
      id: 'usage-trend',
      title: 'Usage & sales trend',
      purpose: 'How much product was used/sold over time?',
      type: 'vbar',
      unit: 'used units',
      data: report.usageByDay.slice(-14).map((u) => ({
        label: fmtDate(u.date).replace(/ \d{4}$/, ''),
        value: u.used,
        color: '#3b82f6',
      })),
    });
  }

  return charts;
}

function buildMilkDisposition(
  productionRows: any[],
  transactionRows: FarmAdminReportInput['transactionRows']
): MilkDisposition {
  const milkProduced = productionRows
    .filter((r) => String(r.productName || '').toUpperCase() === 'MILK')
    .reduce((sum, r) => sum + (Number(r.quantity) || 0), 0);

  let sold = 0;
  let consumedOnFarm = 0;
  let consumedByUmucunda = 0;
  let wasteLogged = 0;

  for (const tx of transactionRows || []) {
    if (String(tx.productType || '').toUpperCase() !== 'MILK') continue;
    const qty = Number(tx.quantity) || 0;
    const cat = String(tx.usageCategory || 'SOLD_TO_DAIRY').toUpperCase();
    if (cat === 'USED_ON_FARM') consumedOnFarm += qty;
    else if (cat === 'CONSUMED_BY_UMUCUNDA') consumedByUmucunda += qty;
    else if (cat === 'WASTE' || cat === 'WASTE_OR_LOST' || cat === 'LOST') wasteLogged += qty;
    else sold += qty; // SOLD_TO_DAIRY (default)
  }

  const accounted = sold + consumedOnFarm + consumedByUmucunda + wasteLogged;
  const unaccounted = Math.max(0, milkProduced - accounted);
  const wasteOrLost = wasteLogged + unaccounted;

  return {
    sold: Number(sold.toFixed(2)),
    consumedOnFarm: Number(consumedOnFarm.toFixed(2)),
    consumedByUmucunda: Number(consumedByUmucunda.toFixed(2)),
    wasteOrLost: Number(wasteOrLost.toFixed(2)),
    produced: Number(milkProduced.toFixed(2)),
    accounted: Number(accounted.toFixed(2)),
  };
}

/**
 * Process raw production + usage rows into a full administrative report.
 * Summaries, KPIs, alerts and chart specs are generated automatically.
 */
export function buildFarmAdminReport(input: FarmAdminReportInput): FarmAdminReport {
  const productionRows = input.productionRows ?? [];
  const usageRows = input.usageRows ?? [];

  const productMap = new Map<string, ProductSummary>();
  const dayMap = new Map<string, DailyProduction>();
  const cattleMap = new Map<string, CattleProduction>();
  const sessionMap = new Map<string, { quantity: number; records: number }>();

  let totalQuantity = 0;
  let milkQuantity = 0;
  let morningQuantity = 0;
  let eveningQuantity = 0;

  for (const row of productionRows) {
    const product = String(row.productName || 'UNKNOWN').toUpperCase();
    const qty = Number(row.quantity) || 0;
    const session = sessionKey(row.milkingSession);
    const date = dayKey(row.productionDate);
    const cattle = row.cattle?.tagNumber || 'Unassigned';

    totalQuantity += qty;
    if (product === 'MILK') milkQuantity += qty;
    if (session === 'Morning') morningQuantity += qty;
    if (session === 'Evening') eveningQuantity += qty;

    const p = productMap.get(product) || {
      product,
      quantity: 0,
      unit: unitFor(product),
      records: 0,
    };
    p.quantity += qty;
    p.records += 1;
    productMap.set(product, p);

    if (date) {
      const d = dayMap.get(date) || {
        date,
        quantity: 0,
        morning: 0,
        evening: 0,
        other: 0,
        records: 0,
      };
      d.quantity += qty;
      d.records += 1;
      if (session === 'Morning') d.morning += qty;
      else if (session === 'Evening') d.evening += qty;
      else d.other += qty;
      dayMap.set(date, d);
    }

    const c = cattleMap.get(cattle) || {
      cattle,
      quantity: 0,
      morning: 0,
      evening: 0,
      records: 0,
    };
    c.quantity += qty;
    c.records += 1;
    if (session === 'Morning') c.morning += qty;
    if (session === 'Evening') c.evening += qty;
    cattleMap.set(cattle, c);

    const s = sessionMap.get(session) || { quantity: 0, records: 0 };
    s.quantity += qty;
    s.records += 1;
    sessionMap.set(session, s);
  }

  let revenue = 0;
  let unpaid = 0;
  let used = 0;
  let remaining = 0;
  const usageByDay: DailyUsage[] = usageRows.map(
    (row: DailySaleRow | FarmAdminReportInput['usageRows'][number]) => {
      const produced = Number(row.produced) || 0;
      const sold = Number(row.sold) || 0;
      const rem = Number(row.remaining) || 0;
      const saleValue = Number(row.saleValue) || 0;
      const paid = Number(row.amountPaid) || 0;
      const unpaidAmt = Number(row.unpaid) || 0;
      revenue += saleValue;
      unpaid += unpaidAmt;
      used += sold;
      remaining += rem;
      return {
        date: row.date,
        product: String(row.productType || '').toUpperCase(),
        produced,
        used: sold,
        remaining: rem,
        revenue: saleValue,
        paid,
        unpaid: unpaidAmt,
      };
    }
  );

  const bySession: SessionSummary[] = [...sessionMap.entries()].map(([session, v]) => ({
    session,
    quantity: v.quantity,
    records: v.records,
    sharePct: totalQuantity > 0 ? (v.quantity / totalQuantity) * 100 : 0,
  }));

  const alerts: string[] = [];
  if (!productionRows.length) {
    alerts.push('No production records in the selected period.');
  }
  if (unpaid > 0) {
    alerts.push(`Outstanding unpaid dairy receivables: ${unpaid.toLocaleString()} RWF.`);
  }
  if (remaining > 0 && used === 0) {
    alerts.push(
      'Production recorded with no usage/sales in the period — review stock disposition.'
    );
  }
  const lowDays = [...dayMap.values()].filter((d) => d.quantity > 0 && d.quantity < 1);
  if (lowDays.length >= 3) {
    alerts.push(`${lowDays.length} days with very low recorded production — verify data entry.`);
  }

  const base = {
    farmName: input.farmName || 'Farm',
    from: input.from,
    to: input.to,
    periodLabel: `${fmtDate(input.from)} → ${fmtDate(input.to)}`,
    generatedAt: new Date().toLocaleString('en-GB'),
    generatedBy: input.generatedBy || 'System (auto)',
    kpis: {
      totalRecords: productionRows.length,
      totalQuantity,
      milkQuantity,
      producingCattle: [...cattleMap.keys()].filter((k) => k !== 'Unassigned').length,
      morningQuantity,
      eveningQuantity,
      revenue,
      unpaid,
      used,
      remaining,
    },
    byProduct: [...productMap.values()].sort((a, b) => b.quantity - a.quantity),
    byDay: [...dayMap.values()].sort((a, b) => a.date.localeCompare(b.date)),
    byCattle: [...cattleMap.values()].sort((a, b) => b.quantity - a.quantity),
    bySession,
    usageByDay: usageByDay.sort((a, b) => String(a.date).localeCompare(String(b.date))),
    milkDisposition: buildMilkDisposition(productionRows, input.transactionRows),
    alerts,
  };

  return {
    ...base,
    autoGenerated: true,
    charts: buildAutoCharts(base),
  };
}
