import type { FarmAdminReport } from './farmAdminReport.types';
import {
  buildWordDocBlob,
  buildWordDocHtml,
  downloadBlob,
  escapeHtml,
  fmtDate,
  fmtNum,
} from './reportBrand';
import {
  htmlDataTable,
  htmlDonutChart,
  htmlHBarChart,
  htmlKpiCard,
  htmlLineChart,
  htmlNeedsAttention,
  htmlShareChart,
  htmlVBarChart,
} from './reportCharts';

export function buildFarmAdminReportDocBody(report: FarmAdminReport) {
  const morningShare =
    report.kpis.totalQuantity > 0
      ? (report.kpis.morningQuantity / report.kpis.totalQuantity) * 100
      : 0;
  const eveningShare =
    report.kpis.totalQuantity > 0
      ? (report.kpis.eveningQuantity / report.kpis.totalQuantity) * 100
      : 0;

  const needsItems = report.alerts.map((a) => {
    if (a.toLowerCase().includes('unpaid')) {
      return { alert: 'Outstanding receivables', example: a, action: 'Review payments' };
    }
    if (a.toLowerCase().includes('no production')) {
      return { alert: 'Missing production', example: a, action: 'Check data entry' };
    }
    if (a.toLowerCase().includes('low')) {
      return { alert: 'Low production days', example: a, action: 'Investigate' };
    }
    return { alert: 'Attention required', example: a, action: 'Review' };
  });

  const chartPanels = (report.charts || []).map((chart) => {
    if (chart.type === 'donut') {
      return htmlDonutChart(chart.title, chart.purpose, chart.data, chart.unit || 'L');
    }
    if (chart.type === 'line' && chart.series?.length) {
      return htmlLineChart(chart.title, chart.purpose, chart.series, {
        yAxisLabel: chart.yAxisLabel || 'Quantity',
        unit: chart.unit,
      });
    }
    if (chart.type === 'share') return htmlShareChart(chart.title, chart.purpose, chart.data);
    if (chart.type === 'vbar') {
      return htmlVBarChart(chart.title, chart.purpose, chart.data, chart.unit);
    }
    return htmlHBarChart(chart.title, chart.purpose, chart.data);
  });

  // Daily production + milk donut span full width; other charts pair in 2-col grid
  const wideIds = new Set(['daily-trend', 'milk-consumed']);
  const chartRows: string[] = [];
  let i = 0;
  while (i < chartPanels.length) {
    const chart = report.charts[i];
    if (chart && wideIds.has(chart.id)) {
      chartRows.push(`<tr><td colspan="2">${chartPanels[i]}</td></tr>`);
      i += 1;
      continue;
    }
    const left = chartPanels[i];
    const right = chartPanels[i + 1];
    const rightChart = report.charts[i + 1];
    if (right && rightChart && !wideIds.has(rightChart.id)) {
      chartRows.push(`<tr><td>${left}</td><td>${right}</td></tr>`);
      i += 2;
    } else {
      chartRows.push(`<tr><td colspan="2">${left}</td></tr>`);
      i += 1;
    }
  }

  return `
    <div class="report-header">
      <h1>DiFarm — Monthly Farm Administrative Report</h1>
      <p class="meta">
        ${escapeHtml(report.farmName)} · ${escapeHtml(report.periodLabel)}<br/>
        Generated ${escapeHtml(report.generatedAt)} · By ${escapeHtml(report.generatedBy)}
        ${report.autoGenerated ? ' · Auto-processed from live farm data' : ''}
      </p>
    </div>

    <p class="layout-note">
      This documentation report is generated automatically. The system aggregates production and usage
      records, computes KPI summaries and charts, then embeds them into this document.
      Layout: KPI cards → charts → needs attention → operational tables.
    </p>

    <div class="wireframe-label">Level 1 · KPI cards (auto-summarized)</div>
    <table class="kpi-table">
      <tr>
        ${htmlKpiCard('Milk produced', fmtNum(report.kpis.milkQuantity), 'Litres this period')}
        ${htmlKpiCard('Production records', String(report.kpis.totalRecords), 'entries logged')}
        ${htmlKpiCard('Cattle producing', String(report.kpis.producingCattle), 'animals with yield')}
        ${htmlKpiCard('Dairy revenue', fmtNum(report.kpis.revenue, 0), 'RWF sale value')}
      </tr>
      <tr>
        ${htmlKpiCard('Morning yield', fmtNum(report.kpis.morningQuantity), `${fmtNum(morningShare, 1)}% of total`)}
        ${htmlKpiCard('Evening yield', fmtNum(report.kpis.eveningQuantity), `${fmtNum(eveningShare, 1)}% of total`)}
        ${htmlKpiCard('Used / sold', fmtNum(report.kpis.used), 'units disposition')}
        ${htmlKpiCard('Unpaid', fmtNum(report.kpis.unpaid, 0), report.kpis.unpaid > 0 ? 'Review required' : 'Clear')}
      </tr>
    </table>

    <div class="wireframe-label">Level 2 · Charts (auto-generated from summaries)</div>
    <table class="charts-grid">
      ${
        chartRows.join('') ||
        '<tr><td colspan="2"><p class="chart-empty">No chart data for this period yet.</p></td></tr>'
      }
    </table>

    <div class="wireframe-label">Level 3 · Needs attention (auto-detected)</div>
    ${htmlNeedsAttention(needsItems)}

    <div class="wireframe-label">Level 4 · Operational tables (auto-aggregated)</div>
    <h2>Production by product</h2>
    ${htmlDataTable(
      ['Product', 'Quantity', 'Unit', 'Records', 'Share of volume'],
      report.byProduct.map((r) => [
        r.product,
        fmtNum(r.quantity),
        r.unit,
        r.records,
        report.kpis.totalQuantity
          ? `${fmtNum((r.quantity / report.kpis.totalQuantity) * 100, 1)}%`
          : '—',
      ])
    )}

    <h2>Morning vs evening sessions</h2>
    ${htmlDataTable(
      ['Session', 'Quantity', 'Records', 'Share %'],
      report.bySession.map((r) => [
        r.session,
        fmtNum(r.quantity),
        r.records,
        `${fmtNum(r.sharePct, 1)}%`,
      ])
    )}

    <h2>Daily production totals</h2>
    ${htmlDataTable(
      ['Date', 'Total', 'Morning', 'Evening', 'Other', 'Records'],
      report.byDay.map((r) => [
        fmtDate(r.date),
        fmtNum(r.quantity),
        fmtNum(r.morning),
        fmtNum(r.evening),
        fmtNum(r.other),
        r.records,
      ])
    )}

    <h2>Production by cattle</h2>
    ${htmlDataTable(
      ['Cattle', 'Total', 'Morning', 'Evening', 'Records'],
      report.byCattle.map((r) => [
        r.cattle,
        fmtNum(r.quantity),
        fmtNum(r.morning),
        fmtNum(r.evening),
        r.records,
      ])
    )}

    ${
      report.usageByDay.length
        ? `<h2>Usage &amp; sales summary</h2>
    ${htmlDataTable(
      ['Date', 'Product', 'Available', 'Used', 'Remaining', 'Revenue', 'Paid', 'Unpaid'],
      report.usageByDay.map((r) => [
        fmtDate(r.date),
        r.product,
        fmtNum(r.produced),
        fmtNum(r.used),
        fmtNum(r.remaining),
        fmtNum(r.revenue, 0),
        fmtNum(r.paid, 0),
        fmtNum(r.unpaid, 0),
      ])
    )}`
        : ''
    }
  `;
}

export function farmAdminReportDocTitle(report: FarmAdminReport) {
  return `DiFarm Farm Admin Report — ${report.farmName}`;
}

export function farmAdminReportDocFilename(report: FarmAdminReport) {
  const stamp = `${report.from}_${report.to}`.replace(/[^0-9-_]/g, '');
  return `DiFarm-farm-admin-report-${stamp}.doc`;
}

export function buildFarmAdminReportDocHtml(report: FarmAdminReport) {
  return buildWordDocHtml(farmAdminReportDocTitle(report), buildFarmAdminReportDocBody(report));
}

export function buildFarmAdminReportDocBlob(report: FarmAdminReport) {
  return buildWordDocBlob(farmAdminReportDocTitle(report), buildFarmAdminReportDocBody(report));
}

export function generateFarmAdminReportDoc(report: FarmAdminReport) {
  const blob = buildFarmAdminReportDocBlob(report);
  downloadBlob(farmAdminReportDocFilename(report), blob);
  return blob;
}
