export type FarmAdminReportInput = {
  farmName: string;
  from: string;
  to: string;
  generatedBy?: string;
  productionRows: any[];
  usageRows: Array<{
    id: string;
    date: string;
    productType: string;
    produced: number;
    sold: number;
    remaining: number;
    saleValue: number;
    amountPaid: number;
    unpaid: number;
    farmName?: string;
  }>;
  /** Raw production-usage transactions (for milk disposition pie). */
  transactionRows?: Array<{
    date?: string;
    productType?: string;
    usageCategory?: string;
    quantity?: number;
  }>;
};

export type ProductSummary = {
  product: string;
  quantity: number;
  unit: string;
  records: number;
};

export type DailyProduction = {
  date: string;
  quantity: number;
  morning: number;
  evening: number;
  other: number;
  records: number;
};

export type CattleProduction = {
  cattle: string;
  quantity: number;
  morning: number;
  evening: number;
  records: number;
};

export type SessionSummary = {
  session: string;
  quantity: number;
  records: number;
  sharePct: number;
};

export type DailyUsage = {
  date: string;
  product: string;
  produced: number;
  used: number;
  remaining: number;
  revenue: number;
  paid: number;
  unpaid: number;
};

export type MilkDisposition = {
  sold: number;
  consumedOnFarm: number;
  consumedByUmucunda: number;
  wasteOrLost: number;
  produced: number;
  accounted: number;
};

export type ReportChartSpec = {
  id: string;
  title: string;
  purpose: string;
  type: 'hbar' | 'vbar' | 'share' | 'line' | 'donut';
  unit?: string;
  yAxisLabel?: string;
  /** Single-series charts (hbar / vbar / share / donut). */
  data: Array<{ label: string; value: number; color?: string }>;
  /** Multi-series line chart (e.g. daily production trend). */
  series?: Array<{
    name: string;
    color: string;
    points: Array<{ label: string; value: number }>;
  }>;
};

export type FarmAdminReport = {
  farmName: string;
  from: string;
  to: string;
  periodLabel: string;
  generatedAt: string;
  generatedBy: string;
  /** True when summaries/charts were computed automatically from live records. */
  autoGenerated: boolean;
  kpis: {
    totalRecords: number;
    totalQuantity: number;
    milkQuantity: number;
    producingCattle: number;
    morningQuantity: number;
    eveningQuantity: number;
    revenue: number;
    unpaid: number;
    used: number;
    remaining: number;
  };
  byProduct: ProductSummary[];
  byDay: DailyProduction[];
  byCattle: CattleProduction[];
  bySession: SessionSummary[];
  usageByDay: DailyUsage[];
  milkDisposition: MilkDisposition;
  /** Auto-built chart specs for documentation (Word/PDF). */
  charts: ReportChartSpec[];
  alerts: string[];
};
